# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dbf8e5d9db49f676e8c4c97cc526f387bcc376ec63cc2c05fcf8451d7b7973b79def0116f6e6e5237b4bf3b52e5560c535dcf0e59121cd4e06e0d57390f6fb89

test:
  secret_key_base: 80a716dfae34a1fb5374418c8c72fd0f53bebf1c2e4b3367121bc28f0d871de321e7109ad2832e47b4c1742faa135c518343ad67372c78e52aea226e6abab625

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
